# -*- coding: utf-8 -*-
"""02.Quick_Numpy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_xoOAj-NI7twqghP-tkVd_c8X8mxjGV
"""

import numpy as np

data1 = [1, 2, 3]
data2 = [4, 5, 6]
data1+data2

data1 = np.array([1, 2, 3])
print(data1, type(data1))

data1.shape

data1.ndim

data2 = np.array([
    [1,2,3],
    [4,5,6],
])
print(data2.shape, data2.ndim)

print(data1.dtype, data2.dtype)

print(data1.size, data2.size)

data3 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
print(data2.shape)

data3 = np.array([1, 2, 3, 4, 5, 6])
print(data3)
data3 = data3.reshape(3, 2)
print(data3)

data3 = data3.reshape(3, -1)
print(data3)

import numpy as np
data4 = np.array([ [1,2,3], [4, 5, 6]], dtype=np.float64)
print(data4.shape, data4.ndim, data4.dtype, data4.size)

data4 = np.array([[1,2,3],[4,5,6]], dtype='f8')
print(data4.shape, data4.ndim, data4.dtype, data4.size)
data4 = data4.astype(np.int64)
print(data4.shape, data4.ndim, data4.dtype, data4.size)

data = np.arange(6).reshape(1, 2, 3)
print(data, data.shape)
print(np.transpose(data))
print(np.transpose(data, (1,2,0)).shape)

np.arange(5)

np.arange(1,5)

np.arange(1, 5, 2)

np.linspace(1, 5, 4)

